# Generated by Django 4.2.3 on 2023-07-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationsApp', '0002_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationsApp.account'),
        ),
    ]
